server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotelservice
    username: root
    password: rootpass
    drive-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: configserver:http://localhost:8085

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

okta:
  oauth2:
    issuer: https://dev-40613544.okta.com/oauth2/default
    audience: api://default